FETCHDEPS_VERSION="|UNKNOWN_VERSION|"
DEPS_FILE_FORMAT="deps_name: repository@version"

UPGRADEFILE_DEFAULT="fetchdeps.upgrade.txt"
INSTALLFILE_DEFAULT="fetchdeps.install.txt"
DEPSFOLDER_DEFAULT="deps"

DEPS_UPGRADE=${FETCHDEPS_UPGRADE_FILE:-${UPGRADEFILE_DEFAULT}}
DEPS_INSTALL=${FETCHDEPS_INSTALL_FILE:-${INSTALLFILE_DEFAULT}}
DEPS_FOLDER=${FETCHDEPS_DEPS_FOLDER:-${DEPSFOLDER_DEFAULT}}

DEPS_PERDEP_INSTALLED_FILE=fetchdeps.installed.txt

VERBOSE=${VERBOSE:-0}
FORCE=${FORCE:-0}